# Generated by Django 3.1.6 on 2021-03-14 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210314_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
