# Generated by Django 3.1.6 on 2021-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210308_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='id',
        ),
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
