# Generated by Django 3.1.6 on 2021-03-13 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210308_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.CharField(default='userx', max_length=503),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.CharField(max_length=50),
        ),
    ]
