# Generated by Django 3.1.6 on 2021-03-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210314_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='track_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
